### PR TITLE
update_to_SDK_4.2.4

### PR DESCRIPTION
**Pull request by sucv**
Hi Xianpi,

Recently I updated the Live2D SDK version to the newest 4.2.4 version. You may consider merging it with yours.

The code has a strange glitch, on both your version and this new version. Allow me to descript the glitch.

First, a summary of my environment:

+ Windows 11
+ Qt6.5.0 (I tried using Qt 6.4.3 but the glitch still exists)
+ MSVC16.11

image

Several weeks ago, the code worked fine on my Ubuntu 20 with GCC. At that time, I didn't try it on my Win10. Recently I upgraded to Win11, and I got this glitch showing below.

Launching the project, everything is normal,
image

Then clicking the "Change Model" button, seems still normal.
image

Clicking again, something weird happens! The character's eye texture is shown at the bottom left, and her eyes won't close when she blinks!
image

Clicking again, same glitch.
image

Keeping clicking, you will see even the first character (Haru in this case) has the glitch. But, Miku is always normal!

Really appreciate it if you could provide any guidance! Thanks in advance.

### CODE REVIEW

**Comment by duanxianpi** [comment]
Is that problem only on Win11 or it is in Ubuntu as well (for new version SDK)? Right now, I am not available on test it on Win11.

**Comment by sucv** [comment]
I confirmed it won't happen on Ubuntu20 with GCC.  I tried just now.

I also tried it on another Win11 PC just now, and it happened.

I am not sure if it happens on Win10.

In my trial, out of the collections from the Live2d Official website, the following models do not have the glitch:
+ wanko
+ Haru (Not the greeter Haru)
+ Miku 
+ Epsilon
+ shizuku

**Comment by duanxianpi** [comment]
Hi sucv, do you mind push your change to the new **dev** branch. When I open this repo, I didn't realize someone else will push their code. So I just keep one main branch. Now, I think I need another dev branch. After I checking your updates, I will merge the code to the main branch. Thanks!

**Comment by sucv** [comment]
Np! glad to contribute. Shall push to dev.

**Pull request closed without merging**
